//! Fixture extension enums for lichen-extend's cross-crate integration tests.
//! These live in a separate crate from the base enums, which is the point:
//! the carriers generated by `#[enum_ext]` transport variant tokens across
//! the crate boundary.

/// Extension with unit, tuple, and struct variants.
#[lichen_extend::enum_ext]
#[derive(Clone, PartialEq, Debug)]
pub enum Shape {
    Unit,
    Num(u32),
    Rec { x: i32, y: String },
}

/// Extension with explicit discriminants.
#[lichen_extend::enum_ext]
#[derive(Clone, PartialEq, Debug)]
pub enum Tagged {
    A = 1,
    B = 2,
}
