use std::collections::hash_map::Entry;
use std::collections::{HashMap, HashSet};
use std::env::current_dir;
use std::hash::RandomState;
use std::io::Write;
use std::iter::once;
use std::ops::Deref;
use std::{fmt::Display, fs::OpenOptions};

use by_address::ByAddress;

use code::{GeneratedBinPath, GeneratedLibPath, GenericsOf, WrittenPath};
use plugin::EqualityProjectGeneric;

use crate::project::code::Name;
use crate::{CRATE, OPERATOR_TYPE, PLUGIN};

pub mod code;
pub mod plugin;

pub static AST_NAME: Name = Name {
    name: "Ast",
    generics: &Generics::none(),
    project_generic: true,
};

pub static AST_IMPL_PATH: WrittenPath = WrittenPath {
    crate_: CRATE,
    path: "ast::AstImpl",
    generics: &Generics::none(),
    project_generic: true,
};

pub static PROPERTIES_COUNT: &'static str = "PROPERTIES_COUNT";

impl Plugin {
    pub fn generate(&'static self) -> std::io::Result<()> {
        let project = Project::new(self);

        let current_dir = current_dir()?;
        CTX.set(Some(Context {
            current: GenerateStage::Lib,
            plugin: self,
        }));
        let lib_path = current_dir
            .join(self.lib_crate_path)
            .join("src")
            .join(self.lib_module.relative)
            .with_extension("rs");
        println!("generate lib at: {}", lib_path.to_string_lossy());
        let mut file = OpenOptions::new()
            .write(true)
            .truncate(true)
            .create(true)
            .open(&lib_path)?;

        writeln!(
            file,
            "// This file is @generated by the {} plugin codegen. Do not edit by hand.",
            self.name
        )?;
        writeln!(file, "{}", DisplayProjectLib(&project))?;
        drop(file);
        CTX.set(Some(Context {
            current: GenerateStage::Bin,
            plugin: self,
        }));
        let bin_path = match &self.bin_module {
            Module::Symbol { crate_path, symbol } => current_dir
                .join(crate_path)
                .join("src")
                .join(symbol.relative),
            Module::Path(path) => current_dir.join(path),
        }
        .with_extension("rs");
        println!("generate bin at: {}", bin_path.to_string_lossy());
        let mut file = OpenOptions::new()
            .write(true)
            .truncate(true)
            .create(true)
            .open(&bin_path)?;
        writeln!(
            file,
            "// This file is @generated by the {} plugin codegen. Do not edit by hand.",
            self.name
        )?;
        writeln!(file, "{}", DisplayProjectBin(&project))?;
        drop(file);

        for path in [&lib_path, &bin_path] {
            if let Err(e) = std::process::Command::new("rustfmt")
                .arg(path)
                .current_dir(&current_dir)
                .status()
            {
                eprintln!(
                    "warning: failed to run rustfmt on {}: {}",
                    path.display(),
                    e
                );
            }
        }

        CTX.set(None);
        Ok(())
    }
}

pub struct ArrayDisplay<'a>(pub &'a [&'static (dyn Display + Sync)]);
impl Display for ArrayDisplay<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for i in self.0 {
            write!(f, "{i}")?;
        }
        Ok(())
    }
}

#[derive(Clone, Copy)]
pub enum GenerateStage {
    Lib,
    Bin,
}

#[derive(Clone, Copy)]
pub struct Context {
    pub current: GenerateStage,
    pub plugin: &'static Plugin,
}

pub struct Delegate<'a, T>(pub &'a T);
pub struct Impl<'a, T, P: Display> {
    pub this: &'a T,
    pub project: &'a P,
}

thread_local! {
    pub static CTX: std::cell::Cell<Option<Context>> = std::cell::Cell::new(None);
}

pub static PROJECT: &'static str = "Project";
pub static PROJECT_TRAIT: Symbol = Symbol::ThisGeneratedLib {
    relative: "",
    name: PROJECT,
};
pub static PROJECT_BASE_TRAIT: WrittenSymbol = WrittenSymbol {
    crate_: LICHEN_CORE,
    relative: "ProjectBase",
};
pub static PROJECT_VARIABLE: &'static str = "P";
pub static PROJECT_GENERIC: Generic = Generic {
    name: PROJECT_VARIABLE,
    constraints: &[&PROJECT_TRAIT],
};
pub static AST: &'static str = "Ast";
pub static AST_TRAIT: WrittenSymbol = WrittenSymbol {
    crate_: LICHEN_CORE,
    relative: "ast::Ast",
};
pub static AST_IMPL: WrittenSymbol = WrittenSymbol {
    crate_: LICHEN_CORE,
    relative: "ast::AstImpl",
};
pub static LICHEN_CORE: &'static str = "lichen_core";
pub static EXPR_ID: WrittenSymbol = WrittenSymbol {
    crate_: LICHEN_CORE,
    relative: "ast::ExprId",
};
pub static NODE_ID_LOCAL: WrittenSymbol = WrittenSymbol {
    crate_: LICHEN_CORE,
    relative: "runtime::NodeIdLocal",
};
pub static EVALUATION: WrittenSymbol = WrittenSymbol {
    crate_: LICHEN_CORE,
    relative: "runtime::evaluation::Evaluation",
};
pub static PHANTOM_DATA: &'static str = "core::marker::PhantomData";

pub struct AsTrait<This: Display, Trait: Display> {
    pub this: This,
    pub trait_: Trait,
}
impl<This: Display, Trait: Display> Display for AsTrait<This, Trait> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "<{} as {}>", self.this, self.trait_)
    }
}

pub static PARTIAL_EQ: Trait = Trait {
    symbol: &Symbol::Raw("PartialEq"),
    functions: &[
        Function {
            name: "eq",
            generics: &Generics::none(),
            self_: Some(Self_(PassMode::Ref { lifetime: None })),
            params: &Params(&[&Param {
                name: "other",
                pass_mode: PassMode::Ref { lifetime: None },
                symbol: &SELF_SYMBOL,
                mutable: false,
            }]),
            return_: Some(Annotation {
                impl_: false,
                symbol: &BOOL_SYMBOL,
            }),
            body: Some(&PartialEqBody { eq_or_ne: true }),
            default_body: None,
        },
        Function {
            name: "ne",
            generics: &Generics::none(),
            self_: Some(Self_(PassMode::Ref { lifetime: None })),
            params: &Params(&[&Param {
                name: "other",
                pass_mode: PassMode::Ref { lifetime: None },
                symbol: &SELF_SYMBOL,
                mutable: false,
            }]),
            return_: Some(Annotation {
                impl_: false,
                symbol: &BOOL_SYMBOL,
            }),
            body: Some(&PartialEqBody { eq_or_ne: false }),
            default_body: None,
        },
    ],
};

pub static HASH: Trait = Trait {
    symbol: &Symbol::Raw("std::hash::Hash"),
    functions: &[Function {
        name: "hash",
        generics: &Generics(&[&Generic {
            name: "H",
            constraints: &[&Symbol::Raw("std::hash::Hasher")],
        }]),
        self_: Some(Self_(PassMode::Ref { lifetime: None })),
        params: &Params(&[&Param {
            name: "state",
            pass_mode: PassMode::RefMut { lifetime: None },
            symbol: &Symbol::Raw("H"),
            mutable: false,
        }]),
        return_: None,
        body: Some(&HashBody),
        default_body: None,
    }],
};

pub static DEBUG: Trait = Trait {
    symbol: &Symbol::Raw("std::fmt::Debug"),
    functions: &[Function {
        name: "fmt",
        generics: &Generics::none(),
        self_: Some(Self_(PassMode::Ref { lifetime: None })),
        params: &Params(&[&FORMATTER_PARAM]),
        return_: Some(Annotation {
            impl_: false,
            symbol: &FORMATE_RESULT_SYMBOL,
        }),
        body: Some(&DebugBody),
        default_body: None,
    }],
};

pub static CLONE: Trait = Trait {
    symbol: &Symbol::Raw("Clone"),
    functions: &[Function {
        name: "clone",
        generics: &Generics::none(),
        self_: Some(Self_(PassMode::Ref { lifetime: None })),
        params: &Params(&[]),
        return_: Some(Annotation {
            impl_: false,
            symbol: &SELF_SYMBOL,
        }),
        body: Some(&CloneBody),
        default_body: None,
    }],
};

pub static FORMATTER_PARAM: Param = Param {
    name: "f",
    pass_mode: PassMode::RefMut { lifetime: None },
    symbol: &Symbol::Raw("std::fmt::Formatter<'_>"),
    mutable: false,
};

pub static FORMATE_RESULT_SYMBOL: Symbol = Symbol::Raw("std::fmt::Result");

pub static SELF_SYMBOL: Symbol = Symbol::Self_;
pub static BOOL_SYMBOL: Symbol = Symbol::Raw("bool");

pub static PRINCIPAL_TRAITS: &'static str = "principal_traits";
pub static MANUALLY_DROP: &'static str = "std::mem::ManuallyDrop";

pub struct EnumType {
    pub name: &'static code::Name,
    pub is_unit: bool,
    pub derives: &'static Derives,
    pub markers: &'static [&'static str],
    pub impls: &'static [&'static Trait],
    pub base_traits: &'static [Symbol],
    pub functions: &'static [Function],
    pub use_enum_types: &'static [&'static EnumType],
    pub plugin: &'static Plugin,
}

pub struct ThisGeneratedLib;
impl Display for ThisGeneratedLib {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let ctx = CTX.get().unwrap();
        write!(f, "{}", ctx.plugin.lib_module)
    }
}

#[derive(Clone, Copy)]
pub enum Symbol {
    Written(&'static WrittenSymbol),
    GeneratedLib {
        plugin: &'static Plugin,
        relative: &'static str,
        name: &'static (dyn Display + Sync),
    },
    Raw(&'static str),
    Dyn(&'static (dyn Display + Sync)),
    ThisGeneratedLib {
        relative: &'static str,
        name: &'static str,
    },
    GeneratedBin {
        relative: &'static str,
        name: &'static str,
    },
    Self_,
}

impl Display for Symbol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Symbol::Written(symbol) => write!(f, "{}", symbol),
            Symbol::GeneratedLib {
                plugin,
                relative,
                name,
            } => {
                write!(f, "{}", plugin.lib_module)?;
                if !relative.is_empty() {
                    write!(f, "::{relative}")?;
                }
                write!(f, "::{name}")?;
                Ok(())
            }
            Symbol::Raw(symbol) => write!(f, "{}", symbol),
            Symbol::Dyn(symbol) => write!(f, "{}", symbol),
            Symbol::ThisGeneratedLib { relative, name } => {
                write!(f, "{ThisGeneratedLib}")?;
                if !relative.is_empty() {
                    write!(f, "::{relative}")?;
                }
                writeln!(f, "::{}", name)?;
                Ok(())
            }
            Symbol::GeneratedBin { relative, name } => {
                write!(f, "crate")?;
                if !relative.is_empty() {
                    write!(f, "::{relative}")?;
                }
                writeln!(f, "::{}", name)?;
                Ok(())
            }
            Symbol::Self_ => write!(f, "Self"),
        }
    }
}

#[derive(Clone, Copy)]
pub struct Annotation {
    pub impl_: bool,
    pub symbol: &'static (dyn Display + Sync),
}

impl Display for Annotation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}{}",
            if self.impl_ { "impl " } else { "" },
            self.symbol
        )
    }
}

pub struct Generic {
    pub name: &'static str,
    pub constraints: &'static [&'static Symbol],
}

impl Display for Generic {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: ", self.name)?;
        for constraint in self.constraints {
            write!(f, "{}+", constraint)?;
        }
        Ok(())
    }
}

pub struct Generics(pub &'static [&'static Generic]);

impl Generics {
    pub const fn none() -> Self {
        Self(&[])
    }
}

impl Display for Generics {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for generic in self.0 {
            write!(f, "{}", generic)?;
        }
        Ok(())
    }
}

impl Display for Delegate<'_, Generics> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for generic in self.0.0 {
            write!(f, "{},", generic.name)?;
        }
        Ok(())
    }
}

pub struct Plugin {
    pub name: &'static str,
    pub lib_crate_path: &'static str,
    pub lib_module: WrittenSymbol,
    pub bin_module: Module,
    pub dependencies: &'static [&'static Plugin],
    pub enum_types: &'static [&'static EnumType],
    pub plugin_enums: &'static [(&'static EnumType, &'static PluginEnum)],
    pub properties: &'static [&'static str],
    pub exprs: &'static [&'static Expr],
    pub expr_impls: &'static [ExprImpls],
}

pub struct Expr {
    pub name: &'static str,
    pub params: &'static ExprParams,
}

pub struct ExprParams(pub &'static [ExprParam]);

impl Display for ExprParams {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for param in self.0 {
            write!(f, "{}:", param.name)?;
            if !param.is_array {
                write!(f, "&{EXPR_ID}")?;
            } else {
                write!(f, "&[{EXPR_ID}]")?;
            }
            write!(f, ",")?;
        }
        Ok(())
    }
}

impl Display for Delegate<'_, ExprParams> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for param in self.0.0 {
            write!(f, "{},", param.name)?;
        }
        Ok(())
    }
}

pub struct ExprParam {
    pub name: &'static str,
    pub is_array: bool,
}

pub struct ExprImpls {
    pub expr: &'static Expr,
    pub impls: &'static [&'static WrittenSymbol],
}

pub enum Module {
    Symbol {
        crate_path: &'static str,
        symbol: WrittenSymbol,
    },
    Path(&'static str),
}

pub struct Project {
    plugin: &'static Plugin,
    ctx: Ctx,
}

impl Project {
    pub fn new(plugin: &'static Plugin) -> Self {
        let mut ctx = Ctx::default();
        fn collect(plugin: &'static Plugin, ctx: &mut Ctx) {
            if let Entry::Vacant(entry) = ctx.plugins.entry(ByAddress(plugin)) {
                entry.insert((
                    HashSet::from_iter(plugin.enum_types.iter().map(|x| ByAddress(*x))),
                    HashSet::new(),
                ));
                for (enum_type, plugin_enum) in plugin.plugin_enums {
                    debug_assert!(
                        ctx.plugin_enums
                            .entry(ByAddress(enum_type))
                            .or_default()
                            .insert(ByAddress(plugin_enum.plugin), plugin_enum)
                            .is_none()
                    );
                }
                for expr_impls in plugin.expr_impls {
                    ctx.expr_impls
                        .entry(ByAddress(expr_impls.expr))
                        .or_default()
                        .extend(expr_impls.impls.iter().map(|x| (*x, plugin)));
                }
                for dependency in plugin.dependencies.iter().copied() {
                    collect(dependency, ctx);
                    let [
                        Some((this_enum_types, this_ancestors)),
                        Some((dependency_enum_type, dependency_ancestors)),
                    ] = ctx
                        .plugins
                        .get_disjoint_mut([&ByAddress(plugin), &ByAddress(dependency)])
                    else {
                        unreachable!()
                    };
                    this_enum_types.extend(dependency_enum_type.iter());
                    this_ancestors.insert(ByAddress(dependency));
                    this_ancestors.extend(dependency_ancestors.iter());
                }
                for enum_type in &ctx.plugins[&ByAddress(plugin)].0 {
                    ctx.enum_types.entry(*enum_type).or_default().push(plugin);
                }
            }
        }
        collect(&plugin, &mut ctx);
        Self { plugin, ctx }
    }
    pub fn fmt_lib(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        {
            writeln!(f, "pub mod {PRINCIPAL_TRAITS}{{")?;
            for enum_type in self.plugin.enum_types {
                write!(f, "pub trait {}: ", enum_type.name)?;
                for base in enum_type.base_traits {
                    write!(f, "{}+", base)?;
                }
                writeln!(f, "{{")?;
                for function in enum_type.functions {
                    write!(f, "{}", function)?;
                }
                writeln!(f, "}}")?;
            }

            {
                write!(f, "pub trait {AST_NAME}: ")?;
                writeln!(f, "{{")?;
                writeln!(f, "const {PROPERTIES_COUNT}: usize;")?;
                writeln!(f, "fn impl_(&self)->&{};", Delegate(&AST_IMPL_PATH))?;
                writeln!(
                    f,
                    "fn impl_mut(&mut self)->&mut {};",
                    Delegate(&AST_IMPL_PATH)
                )?;
                writeln!(f, "}}")?;
            }
            writeln!(f, "}}")?;
        }

        {
            write!(
                f,
                "pub trait {PROJECT}: std::fmt::Debug+Default+Copy+Eq+std::hash::Hash+'static+"
            )?;
            for dependency in self.plugin.dependencies {
                write!(f, "{}::{PROJECT}+", dependency.lib_module)?;
            }
            writeln!(f, "")?;
            writeln!(f, "{{")?;
            for name in self.plugin.enum_types.iter().map(|x| x.name).chain(
                if ByAddress(self.plugin) == ByAddress(&PLUGIN) {
                    Some(&AST_NAME)
                } else {
                    None
                },
            ) {
                writeln!(
                    f,
                    "type {}: {} + {};",
                    name.non_project_generic(),
                    Delegate(&Impl {
                        this: &GeneratedLibPath {
                            plugin: self.plugin,
                            relative: PRINCIPAL_TRAITS,
                            name
                        },
                        project: &SELF_SYMBOL
                    }),
                    Delegate(&Impl {
                        this: &GeneratedLibPath {
                            plugin: self.plugin,
                            relative: "",
                            name
                        },
                        project: &SELF_SYMBOL
                    })
                )?;
            }
            writeln!(f, "}}")?;
        }

        let plugin_enums = HashMap::<_, _, RandomState>::from_iter(
            self.plugin
                .plugin_enums
                .iter()
                .map(|(enum_type, plugin_enum)| (ByAddress(*enum_type), *plugin_enum)),
        );
        for (enum_type, _) in &self.ctx.enum_types {
            let plugin_enum = plugin_enums.get(enum_type);
            writeln!(f, "pub trait {}: ", enum_type.name,)?;
            for dependency in self.plugin.dependencies {
                write!(
                    f,
                    "{}+",
                    Delegate(&GeneratedLibPath {
                        plugin: dependency,
                        relative: "",
                        name: enum_type.name
                    })
                )?;
            }
            writeln!(f, "{{")?;
            if let Some(plugin_enum) = &plugin_enum {
                if enum_type.is_unit {
                    for variant in plugin_enum.variants.iter() {
                        writeln!(f, "fn {}()->Self;", variant.name)?
                    }
                } else {
                    for variant in plugin_enum.variants.iter() {
                        if variant.is_unit {
                            writeln!(f, "fn {}(&self)->bool;", variant.name)?;
                            writeln!(f, "fn from_{}()->Self;", variant.name)?;
                        } else {
                            writeln!(
                                f,
                                "fn {}(&self)->Option<&{}>;",
                                variant.name,
                                Delegate(variant.path)
                            )?;
                            writeln!(
                                f,
                                "fn from_{}(data: {})->Self;",
                                variant.name,
                                Delegate(variant.path)
                            )?;
                        }
                    }
                }
            }
            writeln!(f, "}}")?;
        }

        write!(
            f,
            "pub trait {AST}<{PROJECT_GENERIC}>: {AST_TRAIT}<{PROJECT_VARIABLE}>+"
        )?;
        for dependency in self.plugin.dependencies {
            write!(f, "{}::{AST}<{PROJECT_VARIABLE}>+", dependency.lib_module)?;
        }
        writeln!(f, "{{")?;
        for property in self.plugin.properties {
            writeln!(f, "fn {property}(&self,expr:&{EXPR_ID})->{NODE_ID_LOCAL};")?;
        }
        writeln!(f, "fn add_literal_{}(&mut self,", self.plugin.name)?;
        for plugin in self.ctx.plugins[&ByAddress(self.plugin)]
            .1
            .iter()
            .map(|x| *x.deref())
            .chain(once(self.plugin))
        {
            for property in plugin.properties {
                write!(f, "{property}: Option<{PROJECT_VARIABLE}::Value>,")?;
            }
        }
        writeln!(f, ")->{EXPR_ID};")?;
        for expr in self.plugin.exprs {
            writeln!(
                f,
                "fn add_{}(&mut self,{})->{EXPR_ID};",
                expr.name, expr.params
            )?;
        }
        writeln!(f, "}}")?;

        writeln!(f, "pub mod expr{{")?;
        for expr in self.plugin.exprs {
            writeln!(f, "pub trait {}<{PROJECT_GENERIC}>{{", expr.name)?;
            writeln!(
                f,
                "fn build(ast:&mut {PROJECT_VARIABLE}::Ast,output:&{EXPR_ID},{});",
                expr.params
            )?;
            writeln!(f, "}}")?;
        }
        writeln!(f, "}}")?;
        Ok(())
    }
    fn fmt_bin(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, "#[derive(Debug,Default,Copy,Clone,PartialEq,Eq,Hash)]")?;
        writeln!(f, "pub struct {PROJECT};")?;
        for (plugin, _) in &self.ctx.plugins {
            writeln!(f, "impl {}::{PROJECT} for {PROJECT}{{", plugin.lib_module)?;
            for name in
                plugin
                    .enum_types
                    .iter()
                    .map(|x| x.name)
                    .chain(if plugin == &ByAddress(&PLUGIN) {
                        Some(&AST_NAME)
                    } else {
                        None
                    })
            {
                writeln!(
                    f,
                    "type {} = {};",
                    name.non_project_generic(),
                    Delegate(&Impl {
                        this: &GeneratedBinPath {
                            relative: "",
                            name: name
                        },
                        project: &"Self"
                    })
                )?;
            }
            writeln!(f, "}}")?;
        }

        {
            writeln!(f, "mod code{{")?;
            for (enum_type, plugin_enums) in &self.ctx.plugin_enums {
                let mut code = 0;
                writeln!(f, "pub(super) mod {}{{", enum_type.name.name)?;
                for (plugin, plugin_enum) in plugin_enums {
                    for variant in plugin_enum.variants {
                        writeln!(
                            f,
                            "pub(in super::super) const {}__{}:usize = {code};",
                            plugin.name, variant.name
                        )?;
                        code += 1;
                    }
                }
                writeln!(f, "}}")?;
            }
            writeln!(f, "}}")?;
        }

        writeln!(f, "mod unions{{")?;
        for (enum_type, plugin_enums) in &self.ctx.plugin_enums {
            if !enum_type.is_unit {
                writeln!(f, "{}", enum_type.derives)?;
                writeln!(f, "pub(super) union {}{{", enum_type.name)?;
                for plugin_enum in plugin_enums.values() {
                    for variant in plugin_enum.variants {
                        writeln!(
                            f,
                            "pub(super) {}__{}: {MANUALLY_DROP}<{}>,",
                            plugin_enum.plugin.name,
                            variant.name,
                            Delegate(variant.path)
                        )?;
                    }
                }
                writeln!(
                    f,
                    "_p: core::marker::PhantomData<({})>",
                    Delegate(&GenericsOf(enum_type.name))
                )?;
                writeln!(f, "}}")?;
            }
        }
        writeln!(f, "}}")?;
        for (enum_type, plugin_enums) in &self.ctx.plugin_enums {
            writeln!(f, "{}", enum_type.derives)?;
            if enum_type.is_unit {
                writeln!(
                    f,
                    "pub struct {}(usize,{PHANTOM_DATA}<{}>);",
                    enum_type.name,
                    Delegate(&GenericsOf(enum_type.name))
                )?;
            } else {
                writeln!(
                    f,
                    "pub struct {}{{code:usize,data:{}}}",
                    enum_type.name,
                    Delegate(&GeneratedBinPath {
                        relative: "unions",
                        name: enum_type.name
                    })
                )?;
            }

            writeln!(
                f,
                "{}",
                MarkersDisplay {
                    markers: enum_type.markers,
                    enum_type
                }
            )?;

            let principle_trait = GeneratedLibPath {
                plugin: enum_type.plugin,
                relative: PRINCIPAL_TRAITS,
                name: enum_type.name,
            };
            let principle_trait = Delegate(&principle_trait);
            let principle_trait = &principle_trait as &(dyn Display + Sync);
            for (trait_, functions) in enum_type
                .impls
                .iter()
                .map(|x| (x.symbol as &(dyn Display + Sync), x.functions))
                .chain(once((principle_trait, enum_type.functions)))
            {
                writeln!(
                    f,
                    "impl<{}> {} for {}",
                    GenericsOf(enum_type.name),
                    trait_,
                    Delegate(&GeneratedBinPath {
                        relative: "",
                        name: enum_type.name
                    }),
                )?;
                if !enum_type.use_enum_types.is_empty() {
                    writeln!(f, "where")?;
                    for use_enum_type in enum_type.use_enum_types {
                        writeln!(
                            f,
                            "{PROJECT_VARIABLE}::{}: {},",
                            Delegate(&use_enum_type.name.non_project_generic()),
                            Delegate(&GeneratedLibPath {
                                plugin: self.plugin,
                                relative: "",
                                name: use_enum_type.name
                            })
                        )?;
                    }
                }
                writeln!(f, "{{")?;
                for function in functions {
                    writeln!(
                        f,
                        "{}{{",
                        FunctionImpl {
                            function,
                            body: None
                        }
                    )?;
                    if let Some(body) = function.body {
                        body.generate_pre_match(f, enum_type, function)?;
                        if enum_type.is_unit {
                            writeln!(f, "match self.0{{")?;
                        } else {
                            writeln!(f, "match self.code{{")?;
                        }
                        for plugin_enum in plugin_enums.values() {
                            for variant in plugin_enum.variants {
                                writeln!(
                                    f,
                                    "self::code::{}::{}__{}=>{{",
                                    enum_type.name.name, plugin_enum.plugin.name, variant.name
                                )?;
                                body.generate_match_branch(
                                    f,
                                    enum_type,
                                    function,
                                    variant,
                                    plugin_enum.plugin,
                                )?;
                                writeln!(f, "}}")?;
                            }
                        }
                        write!(f, "_=>unreachable!(),")?;
                        writeln!(f, "}}")?;
                    } else {
                        writeln!(f, "unimplemented!();")?;
                    }
                    writeln!(f, "}}")?;
                }
                writeln!(f, "}}")?;
            }

            {
                let mut code2variant = Vec::<(&Variant, &Plugin)>::new();
                for plugin in &self.ctx.enum_types[&ByAddress(enum_type)] {
                    writeln!(
                        f,
                        "impl<{}> {} for {}{{",
                        GenericsOf(enum_type.name),
                        Delegate(&GeneratedLibPath {
                            plugin,
                            relative: "",
                            name: enum_type.name
                        }),
                        Delegate(&GeneratedBinPath {
                            relative: "",
                            name: enum_type.name
                        })
                    )?;
                    if let Some(plugin_enum) =
                        self.ctx.plugin_enums[&ByAddress(enum_type)].get(&ByAddress(plugin))
                    {
                        for variant in plugin_enum.variants {
                            code2variant.push((variant, plugin_enum.plugin));
                            if enum_type.is_unit {
                                writeln!(
                                    f,
                                    "fn {}()->Self{{Self(self::code::{}::{}__{},{PHANTOM_DATA})}}",
                                    variant.name,
                                    enum_type.name.name,
                                    plugin_enum.plugin.name,
                                    variant.name
                                )?
                            } else {
                                if variant.is_unit {
                                    writeln!(
                                        f,
                                        "fn {}(&self)->bool{{self.code==self::code::{}::{}__{}}}",
                                        variant.name,
                                        enum_type.name.name,
                                        plugin_enum.plugin.name,
                                        variant.name
                                    )?;
                                    writeln!(
                                        f,
                                        "fn from_{0}()->Self{{Self{{code:self::code::{1}::{3}__{0},data:self::unions::{1}{2}{{{3}__{0}: {MANUALLY_DROP}::new({4})}} }} }}",
                                        variant.name,
                                        enum_type.name.name,
                                        Delegate(enum_type.name.generics),
                                        plugin_enum.plugin.name,
                                        Delegate(variant.path)
                                    )?;
                                } else {
                                    writeln!(
                                        f,
                                        "fn {0}(&self)->Option<&{1}>{{if self.code==self::code::{2}::{3}__{4}{{Some(unsafe{{&self.data.{3}__{4}}})}}else{{None}} }}",
                                        variant.name,
                                        Delegate(variant.path),
                                        enum_type.name.name,
                                        plugin_enum.plugin.name,
                                        variant.name
                                    )?;
                                    writeln!(
                                        f,
                                        "fn from_{0}(data: {1})->Self{{Self{{code:self::code::{2}::{3}__{4},data:self::unions::{2}{{{3}__{4}:{MANUALLY_DROP}::new(data)}} }} }}",
                                        variant.name,
                                        Delegate(variant.path),
                                        enum_type.name.name,
                                        plugin_enum.plugin.name,
                                        variant.name
                                    )?;
                                }
                            }
                        }
                    }
                    writeln!(f, "}}")?;
                }
            }
        }
        let mut properties_count = 0;
        {
            for (plugin, _) in &self.ctx.plugins {
                writeln!(
                    f,
                    "impl<{}> {}::{AST}<{PROJECT_VARIABLE}> for {AST}<{PROJECT_VARIABLE}>",
                    EqualityProjectGeneric {
                        associated: &AST,
                        target: &ArrayDisplay(&[&AST, &"<", &PROJECT_VARIABLE, &">"]),
                    },
                    plugin.lib_module,
                )?;
                writeln!(
                    f,
                    "where {PROJECT_VARIABLE}::{}: {},",
                    Delegate(&OPERATOR_TYPE.name.non_project_generic()),
                    Delegate(&GeneratedLibPath {
                        plugin,
                        relative: "",
                        name: OPERATOR_TYPE.name
                    })
                )?;
                writeln!(f, "{{")?;
                for property in plugin.properties {
                    writeln!(
                        f,
                        "fn {property}(&self,expr:&{EXPR_ID})->{NODE_ID_LOCAL}{{self.impl_.property(expr,{properties_count})}}"
                    )?;
                }
                properties_count += 1;
                writeln!(f, "fn add_literal_{}(&mut self,", plugin.name)?;
                for plugin in self.ctx.plugins[plugin].1.iter().chain(once(plugin)) {
                    for property in plugin.properties {
                        write!(f, "{property}: Option<{PROJECT_VARIABLE}::Value>,")?;
                    }
                }
                writeln!(f, ")->{EXPR_ID}{{")?;
                writeln!(
                    f,
                    "let expr = <Self as {AST_TRAIT}<{PROJECT_VARIABLE}>>::add_auto(self);"
                )?;
                for plugin in self.ctx.plugins[plugin].1.iter().chain(once(plugin)) {
                    for property in plugin.properties {
                        writeln!(f, "if let Some({property}) = {property}{{")?;
                        writeln!(
                            f,
                            "let node = <Self as {}::{AST}<{PROJECT_VARIABLE}>>::{property}(self,&expr);",
                            plugin.lib_module
                        )?;
                        write!(
                            f,
                            "*<Self as {AST_TRAIT}<{PROJECT_VARIABLE}>>::impl_mut(self).module.evaluation_mut(&node)={EVALUATION}::Value({property})"
                        )?;
                        writeln!(f, "}}")?;
                    }
                }
                writeln!(f, "expr")?;
                writeln!(f, "}}")?;
                for expr in plugin.exprs {
                    writeln!(
                        f,
                        "fn add_{}(&mut self,{})->{EXPR_ID}{{",
                        expr.name, expr.params
                    )?;
                    writeln!(
                        f,
                        "let output = <Self as {AST_TRAIT}<{PROJECT_VARIABLE}>>::add_auto(self);"
                    )?;
                    for (expr_impl, plugin) in
                        self.ctx.expr_impls.get(&ByAddress(expr)).unwrap_or(&vec![])
                    {
                        writeln!(
                            f,
                            "<{expr_impl} as {}::expr::{}<{PROJECT_VARIABLE}>>::build(self,&output,{});",
                            plugin.lib_module,
                            expr.name,
                            Delegate(expr.params)
                        )?;
                    }
                    writeln!(f, "output")?;
                    writeln!(f, "}}")?;
                }
                writeln!(f, "}}")?;
            }

            {
                writeln!(f, "pub struct {AST_NAME}{{")?;
                writeln!(f, "pub impl_: {}", Delegate(&AST_IMPL_PATH))?;
                writeln!(f, "}}")?;
            }
            {
                writeln!(
                    f,
                    "impl<{}> {} for {}{{",
                    GenericsOf(&AST_NAME),
                    Delegate(&GeneratedLibPath {
                        plugin: &PLUGIN,
                        relative: PRINCIPAL_TRAITS,
                        name: &AST_NAME
                    }),
                    Delegate(&GeneratedBinPath {
                        relative: "",
                        name: &AST_NAME
                    })
                )?;
                writeln!(f, "const {PROPERTIES_COUNT}: usize = {properties_count};")?;
                writeln!(
                    f,
                    "fn impl_(&self)->&{}{{&self.impl_}}",
                    Delegate(&AST_IMPL_PATH)
                )?;
                writeln!(
                    f,
                    "fn impl_mut(&mut self)->&mut {}{{&mut self.impl_}}",
                    Delegate(&AST_IMPL_PATH)
                )?;
                writeln!(f, "}}")?;
            }
        }
        Ok(())
    }
}

struct DisplayProjectLib<'a>(&'a Project);

impl Display for DisplayProjectLib<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt_lib(f)
    }
}

struct DisplayProjectBin<'a>(&'a Project);

impl Display for DisplayProjectBin<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt_bin(f)
    }
}

#[derive(Default)]
pub struct Ctx {
    plugins: HashMap<
        ByAddress<&'static Plugin>,
        (
            HashSet<ByAddress<&'static EnumType>>,
            HashSet<ByAddress<&'static Plugin>>,
        ),
    >,
    enum_types: HashMap<ByAddress<&'static EnumType>, Vec<&'static Plugin>>,
    plugin_enums: HashMap<
        ByAddress<&'static EnumType>,
        HashMap<ByAddress<&'static Plugin>, &'static PluginEnum>,
    >,
    expr_impls: HashMap<ByAddress<&'static Expr>, Vec<(&'static WrittenSymbol, &'static Plugin)>>,
}
pub struct Derives(pub &'static [&'static str]);
impl Display for Derives {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if !self.0.is_empty() {
            write!(f, "#[derive(")?;
            for derive in self.0 {
                write!(f, "{},", derive)?;
            }
            write!(f, ")]")?;
        }
        Ok(())
    }
}
pub struct MarkersDisplay {
    pub markers: &'static [&'static str],
    pub enum_type: &'static EnumType,
}
impl Display for MarkersDisplay {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for marker in self.markers {
            writeln!(
                f,
                "impl<{}> {} for {}{{}}",
                GenericsOf(self.enum_type.name),
                marker,
                Delegate(&GeneratedBinPath {
                    relative: "",
                    name: self.enum_type.name
                })
            )?;
        }
        Ok(())
    }
}

pub struct PluginEnum {
    pub variants: &'static [Variant],
    pub plugin: &'static Plugin,
}

pub struct Variant {
    pub name: &'static str,
    pub path: &'static WrittenPath,
    pub is_unit: bool,
}

pub struct WrittenSymbol {
    pub crate_: &'static str,
    pub relative: &'static str,
}

impl Display for WrittenSymbol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}::{}", Crate(self.crate_), self.relative)
    }
}

pub struct Crate(&'static str);

impl Display for Crate {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let ctx = CTX.get().unwrap();
        if matches!(ctx.current, GenerateStage::Lib) && ctx.plugin.lib_module.crate_ == self.0 {
            write!(f, "crate")
        } else {
            write!(f, "::{}", self.0)
        }
    }
}

pub struct Trait {
    pub symbol: &'static Symbol,
    pub functions: &'static [Function],
}

pub struct Function {
    pub name: &'static str,
    pub generics: &'static Generics,
    pub self_: Option<Self_>,
    pub params: &'static Params,
    pub return_: Option<Annotation>,
    pub body: Option<&'static dyn Body>,
    pub default_body: Option<&'static (dyn Display + Sync)>,
}

pub struct FunctionImpl<'a> {
    function: &'a Function,
    body: Option<&'a (dyn Display + Sync)>,
}

impl Display for FunctionImpl<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let function = self.function;
        write!(f, "fn {}<{}>(", function.name, function.generics)?;
        if let Some(self_) = function.self_.as_ref() {
            write!(f, "{}", self_)?;
        }
        write!(f, "{})", function.params)?;
        if let Some(return_) = function.return_ {
            write!(f, "->{}", return_)?;
        }
        if let Some(default_body) = self.body {
            writeln!(f, "{{{default_body}}}")?;
        }
        Ok(())
    }
}

impl Display for Function {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if let Some(default_body) = self.default_body {
            write!(
                f,
                "{}",
                FunctionImpl {
                    function: self,
                    body: Some(default_body)
                }
            )?;
        } else {
            write!(
                f,
                "{}",
                FunctionImpl {
                    function: self,
                    body: None
                }
            )?;
            writeln!(f, ";")?;
        }
        Ok(())
    }
}

pub struct Params(pub &'static [&'static Param]);

impl Display for Params {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for param in self.0 {
            write!(f, "{}", param)?;
        }
        Ok(())
    }
}

impl Display for Delegate<'_, Params> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for param in self.0.0 {
            write!(f, "{},", param.name)?;
        }
        Ok(())
    }
}

pub enum PassMode {
    Move,
    Ref { lifetime: Option<&'static str> },
    RefMut { lifetime: Option<&'static str> },
}

impl Display for PassMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PassMode::Move => write!(f, ""),
            PassMode::Ref { lifetime } => write!(f, "&{} ", lifetime.unwrap_or("")),
            PassMode::RefMut { lifetime } => write!(f, "&mut{} ", lifetime.unwrap_or("")),
        }
    }
}

pub struct Self_(pub PassMode);

impl Display for Self_ {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}self,", self.0)
    }
}

pub struct Param {
    pub name: &'static str,
    pub pass_mode: PassMode,
    pub symbol: &'static Symbol,
    pub mutable: bool,
}

impl Display for Param {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}{}: {}{},",
            if self.mutable { "mut " } else { "" },
            self.name,
            self.pass_mode,
            self.symbol
        )
    }
}

pub trait Body: Send + Sync {
    fn generate_pre_match(
        &self,
        f: &mut std::fmt::Formatter<'_>,
        enum_type: &EnumType,
        function: &Function,
    ) -> std::fmt::Result;
    fn generate_match_branch(
        &self,
        f: &mut std::fmt::Formatter<'_>,
        enum_type: &EnumType,
        function: &Function,
        variant: &Variant,
        plugin: &Plugin,
    ) -> std::fmt::Result;
}

pub struct DelegateBody;

impl Body for DelegateBody {
    fn generate_pre_match(
        &self,
        f: &mut std::fmt::Formatter<'_>,
        enum_type: &EnumType,
        function: &Function,
    ) -> std::fmt::Result {
        Ok(())
    }

    fn generate_match_branch(
        &self,
        f: &mut std::fmt::Formatter<'_>,
        enum_type: &EnumType,
        function: &Function,
        variant: &Variant,
        plugin: &Plugin,
    ) -> std::fmt::Result {
        if let Some(return_) = function.return_
            && return_.impl_
        {
            write!(f, "std::boxed::Box::new(")?;
        }
        write!(
            f,
            "<{} as {}>::{}(",
            Delegate(variant.path),
            Delegate(&GeneratedLibPath {
                plugin: enum_type.plugin,
                relative: PRINCIPAL_TRAITS,
                name: enum_type.name
            }),
            function.name
        )?;
        if let Some(self_) = &function.self_ {
            if enum_type.is_unit {
                write!(f, "unsafe{{{}{}}}", self_.0, Delegate(variant.path))?;
            } else {
                write!(
                    f,
                    "unsafe{{{}self.data.{}__{}}}",
                    self_.0, plugin.name, variant.name
                )?;
            }
            write!(f, ",")?;
        }
        for param in function.params.0 {
            if matches!(param.symbol, Symbol::Self_) {
                write!(
                    f,
                    "unsafe{{{}{}.data.{}__{}}},",
                    param.pass_mode, param.name, plugin.name, variant.name
                )?;
            } else {
                write!(f, "{},", param.name)?;
            }
        }
        writeln!(f, ")")?;
        if let Some(return_) = function.return_
            && return_.impl_
        {
            writeln!(f, ") as std::boxed::Box<dyn {}>", return_.symbol)?;
        }
        Ok(())
    }
}

pub struct PartialEqBody {
    pub eq_or_ne: bool,
}

impl Body for PartialEqBody {
    fn generate_pre_match(
        &self,
        f: &mut std::fmt::Formatter<'_>,
        enum_type: &EnumType,
        function: &Function,
    ) -> std::fmt::Result {
        writeln!(f, "if self.code!=other.code{{return {}}}", !self.eq_or_ne)
    }

    fn generate_match_branch(
        &self,
        f: &mut std::fmt::Formatter<'_>,
        enum_type: &EnumType,
        function: &Function,
        variant: &Variant,
        plugin: &Plugin,
    ) -> std::fmt::Result {
        writeln!(
            f,
            "unsafe{{self.data.{0}__{1}{2}other.data.{0}__{1}}}",
            plugin.name,
            variant.name,
            if self.eq_or_ne { "==" } else { "!=" }
        )
    }
}

pub struct HashBody;

impl Body for HashBody {
    fn generate_pre_match(
        &self,
        f: &mut std::fmt::Formatter<'_>,
        enum_type: &EnumType,
        function: &Function,
    ) -> std::fmt::Result {
        writeln!(f, "self.code.hash(state);")
    }

    fn generate_match_branch(
        &self,
        f: &mut std::fmt::Formatter<'_>,
        enum_type: &EnumType,
        function: &Function,
        variant: &Variant,
        plugin: &Plugin,
    ) -> std::fmt::Result {
        writeln!(
            f,
            "unsafe{{&self.data.{0}__{1}}}.hash(state);",
            plugin.name, variant.name,
        )
    }
}

pub struct DebugBody;

impl Body for DebugBody {
    fn generate_pre_match(
        &self,
        f: &mut std::fmt::Formatter<'_>,
        enum_type: &EnumType,
        function: &Function,
    ) -> std::fmt::Result {
        Ok(())
    }

    fn generate_match_branch(
        &self,
        f: &mut std::fmt::Formatter<'_>,
        enum_type: &EnumType,
        function: &Function,
        variant: &Variant,
        plugin: &Plugin,
    ) -> std::fmt::Result {
        write!(f, "write!(f,\"{}::{}", plugin.name, variant.name)?;
        if enum_type.is_unit || variant.is_unit {
            write!(f, "\")")?;
        } else {
            write!(
                f,
                "({{:?}})\",unsafe{{&*self.data.{}__{}}})",
                plugin.name, variant.name
            )?;
        }
        writeln!(f, "")?;
        Ok(())
    }
}

pub struct CloneBody;

impl Body for CloneBody {
    fn generate_pre_match(
        &self,
        f: &mut std::fmt::Formatter<'_>,
        enum_type: &EnumType,
        function: &Function,
    ) -> std::fmt::Result {
        Ok(())
    }

    fn generate_match_branch(
        &self,
        f: &mut std::fmt::Formatter<'_>,
        enum_type: &EnumType,
        function: &Function,
        variant: &Variant,
        plugin: &Plugin,
    ) -> std::fmt::Result {
        writeln!(
            f,
            "Self{{code:self.code,data:self::unions::{0}{{{1}__{2}:unsafe{{&self.data.{1}__{2}}}.clone() }} }}",
            enum_type.name.name, plugin.name, variant.name
        )
    }
}

pub struct VariantData {
    pub variant_name: &'static str,
}

impl Display for VariantData {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "self.data.{}", self.variant_name)
    }
}
