[workspace]
resolver = "3"
members = [
    "crates/lichen-span",
    "crates/lichen-utils",
    "crates/lichen-language-lex",
    "crates/lichen-language-parser",
    "crates/lichen-preprocess",
    "crates/lichen-lowlevel",
    "crates/lichen-highlevel",
    "crates/lichen-compute",
    "crates/lichen-render",
    "crates/lichen-doc",
    "crates/lichen-perspective",
    "crates/lichen-language",
    "crates/lichen-language-server",
    "lichen-language-zed",
    "crates/lichen-package",
    "lichen-std-native",
    "tree-sitter-lichen",
]
