[package]
name = "lichen-language"
version = "0.1.0"
edition = "2024"
default-run = "lichen-compiler"

[dependencies]
logos = "0.16"
sha2 = "0.10"
lichen-compute = { path = "../lichen-compute" }
lichen-doc = { path = "../lichen-doc" }
lichen-highlevel = { path = "../lichen-highlevel" }
lichen-language-lex = { path = "../lichen-language-lex" }
lichen-language-parser = { path = "../lichen-language-parser" }
lichen-perspective = { path = "../lichen-perspective" }
lichen-lowlevel = { path = "../lichen-lowlevel" }
lichen-render = { path = "../lichen-render" }
lichen-utils = { path = "../lichen-utils" }

[dev-dependencies]
lichen-std-native = { path = "../../lichen-std-native" }

[[bin]]
name = "lichen-compiler"
path = "src/main.rs"
