// This file is @generated by the structure plugin codegen. Do not edit by hand.
pub mod principal_traits {
    pub trait Ast<P: crate::plugin::Project> {
        const PROPERTIES_COUNT: usize;
        fn impl_(&self) -> &::lichen_core::ast::AstImpl<P>;
        fn impl_mut(&mut self) -> &mut ::lichen_core::ast::AstImpl<P>;
    }
}
pub trait Project:
    std::fmt::Debug + Default + Copy + Eq + std::hash::Hash + 'static + ::lichen_core::plugin::Project
{
}
pub trait Value: ::lichen_core::plugin::Value {
    fn named_array(&self) -> Option<&crate::value::NamedArray>;
    fn from_named_array(data: crate::value::NamedArray) -> Self;
    fn name_set(&self) -> Option<&crate::value::NameSet>;
    fn from_name_set(data: crate::value::NameSet) -> Self;
    fn structure(&self) -> Option<&crate::value::Structure>;
    fn from_structure(data: crate::value::Structure) -> Self;
}
pub trait Operator<P: crate::plugin::Project>: ::lichen_core::plugin::Operator<P> {
    fn offset() -> Self;
    fn component() -> Self;
}
pub trait DiagnosticKind<P: crate::plugin::Project>:
    ::lichen_core::plugin::DiagnosticKind<P>
{
}
pub trait Ast<P: crate::plugin::Project>:
    ::lichen_core::ast::Ast<P> + ::lichen_core::plugin::Ast<P>
{
    fn structure(&self, expr: &::lichen_core::ast::ExprId) -> ::lichen_core::runtime::NodeIdLocal;
    fn add_literal_structure(
        &mut self,
        value: Option<P::Value>,
        structure: Option<P::Value>,
    ) -> ::lichen_core::ast::ExprId;
    fn add_member(
        &mut self,
        structure: &::lichen_core::ast::ExprId,
        name: &::lichen_core::ast::ExprId,
    ) -> ::lichen_core::ast::ExprId;
}
pub mod expr {
    pub trait member<P: crate::plugin::Project> {
        fn build(
            ast: &mut P::Ast,
            output: &::lichen_core::ast::ExprId,
            structure: &::lichen_core::ast::ExprId,
            name: &::lichen_core::ast::ExprId,
        );
    }
}
