//! Cross-crate enum extension: base enums live here, extension enums in
//! `extend-fixture`; the carriers generated by `#[enum_ext]` splice the
//! extension variants in and provide `From` and `AsEnum` conversions.

use extend_fixture::{extend_Shape, extend_Tagged};
use lichen_utils::extend::AsEnum;

extend_Shape! {
    pub enum Base {
        Own,
    }
}

extend_Shape! {
    pub enum Gen<T> {
        Val(T),
    }
}

extend_Tagged! {
    pub enum TagBase {
        One,
    }
}

#[test]
fn base_gains_all_extension_variants() {
    assert!(matches!(Base::Own, Base::Own));
    assert!(matches!(Base::Unit, Base::Unit));
    assert!(matches!(Base::Num(3), Base::Num(3)));
    assert!(matches!(
        Base::Rec {
            x: 1,
            y: String::new()
        },
        Base::Rec { x: 1, .. }
    ));
}

#[test]
fn from_extension_moves_payloads() {
    assert!(matches!(
        Base::from(extend_fixture::Shape::Num(7)),
        Base::Num(7)
    ));
    assert!(matches!(
        Base::from(extend_fixture::Shape::Rec {
            x: 1,
            y: "t".into()
        }),
        Base::Rec { x: 1, .. }
    ));
}

#[test]
fn as_enum_views_extension_variants_and_none_for_base_own() {
    use extend_fixture::Shape;
    assert_eq!(Base::Num(3).as_enum(), Some(Shape::Num(3)));
    assert_eq!(
        Base::Rec {
            x: 1,
            y: "t".into()
        }
        .as_enum(),
        Some(Shape::Rec {
            x: 1,
            y: "t".into()
        })
    );
    assert_eq!(Base::Unit.as_enum(), Some(Shape::Unit));
    assert_eq!(Base::Own.as_enum(), None);
}

#[test]
fn generic_base_keeps_its_parameters() {
    let g: Gen<String> = extend_fixture::Shape::Num(5).into();
    assert!(matches!(g, Gen::Num(5)));
}

#[test]
fn discriminants_survive_the_splice() {
    assert_eq!(TagBase::One as i32, 0);
    assert_eq!(TagBase::A as i32, 1);
    assert_eq!(TagBase::B as i32, 2);
    let t: TagBase = extend_fixture::Tagged::B.into();
    assert!(matches!(t, TagBase::B));
    assert_eq!(TagBase::B.as_enum(), Some(extend_fixture::Tagged::B));
    assert_eq!(TagBase::One.as_enum(), None);
}
