[package]
name = "lichen-extend"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "parsing", "printing", "clone-impls"] }

[dev-dependencies]
extend-fixture = { path = "../extend-fixture" }
lichen-utils = { path = "../lichen-utils" }
