//! The artifact codec primitives: the byte reader/writer, the per-leaf
//! value/operator codec traits, and the structural leaf codecs.
//!
//! The artifact format (`liche-language::persist`) is generic over a program's
//! value/operator vocabulary; the only vocabulary-dependent parts are the value
//! and operator encodings.  This module isolates them: each value/operator leaf
//! enum implements [`ValueCodec`]/[`OperatorCodec`] for itself, and a composed
//! vocabulary's `ProgramCodec` (generated by `liche-language`'s
//! `lang_compose_vocabulary!`) dispatches each carry variant to its leaf's codec.
//!
//! The lowlevel owns the leaf codec protocol because [`LowValue`]'s handle
//! variants need the arena relocation the artifact container provides, and
//! every lower/leaf crate already depends on the lowlevel for those types.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use crate::{
    AnyFunctionId, AnyHandle, ArrayItem, LowOperator, LowValue, ModuleKey, Program,
    StaticFunctionId, StaticFunctionRef, StaticHandle, StaticModule, TableItem,
};

// --- byte reader / writer -----------------------------------------------------

/// A little-endian byte writer for the artifact format.
pub struct Writer {
    buf: Vec<u8>,
}

impl Writer {
    pub fn new() -> Writer {
        Writer { buf: Vec::new() }
    }
    pub fn u8(&mut self, value: u8) {
        self.buf.push(value);
    }
    pub fn u32(&mut self, value: u32) {
        self.buf.extend_from_slice(&value.to_le_bytes());
    }
    pub fn u64(&mut self, value: u64) {
        self.buf.extend_from_slice(&value.to_le_bytes());
    }
    pub fn bytes(&mut self, bytes: &[u8]) {
        self.buf.extend_from_slice(bytes);
    }
    pub fn path(&mut self, path: &Path) {
        let bytes = path.to_string_lossy();
        self.u32(bytes.len() as u32);
        self.buf.extend_from_slice(bytes.as_bytes());
    }
    /// Write a length-prefixed leaf-name discriminator: a one-byte length then
    /// the name bytes.  The composed `ProgramCodec` tags every value/operator
    /// leaf with its carry-variant name so the reader knows which leaf codec
    /// to dispatch to.
    pub fn leaf(&mut self, name: &str) {
        self.u8(name.len() as u8);
        self.bytes(name.as_bytes());
    }
    pub fn into_bytes(self) -> Vec<u8> {
        self.buf
    }
}

impl Default for Writer {
    fn default() -> Self {
        Writer::new()
    }
}

/// A little-endian byte reader over an artifact buffer.
pub struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    pub fn new(buf: &'a [u8]) -> Reader<'a> {
        Reader { buf, pos: 0 }
    }
    pub fn u8(&mut self) -> Result<u8, String> {
        let byte = *self.buf.get(self.pos).ok_or("truncated artifact")?;
        self.pos += 1;
        Ok(byte)
    }
    pub fn u32(&mut self) -> Result<u32, String> {
        let bytes = self.take(4)?;
        Ok(u32::from_le_bytes(bytes.try_into().expect("4 bytes")))
    }
    pub fn u64(&mut self) -> Result<u64, String> {
        let bytes = self.take(8)?;
        Ok(u64::from_le_bytes(bytes.try_into().expect("8 bytes")))
    }
    pub fn take(&mut self, len: usize) -> Result<&'a [u8], String> {
        if self.pos + len > self.buf.len() {
            return Err("truncated artifact".into());
        }
        let bytes = &self.buf[self.pos..self.pos + len];
        self.pos += len;
        Ok(bytes)
    }
    pub fn path(&mut self) -> Result<PathBuf, String> {
        let len = self.u32()? as usize;
        let bytes = self.take(len)?;
        Ok(PathBuf::from(String::from_utf8_lossy(bytes).into_owned()))
    }
    /// Read a length-prefixed leaf-name discriminator (see [`Writer::leaf`]).
    /// The returned slice borrows the buffer, not the reader, so the reader
    /// stays usable for the leaf payload.
    pub fn leaf_name(&mut self) -> Result<&'a [u8], String> {
        let len = self.u8()? as usize;
        self.take(len)
    }
    pub fn done(&self) -> bool {
        self.pos == self.buf.len()
    }
}

// --- the per-leaf codec traits --------------------------------------------------

/// Encode/decode one **value leaf** enum.
///
/// A composed vocabulary's codec writes a leaf discriminator, then delegates to
/// the matching leaf's `write_value`/`read_value`.  A leaf whose variants carry
/// no arena payload (type markers, plugin scalars) ignores the `modules`/
/// `self_*` context; [`LowValue`]'s handle variants need it to relocate.
///
/// **Contract:** the two sides must be exact inverses — every tag the writer
/// emits, the reader decodes to the equal value, and nothing else.  A mismatch
/// compiles but silently breaks every cache load (a stored artifact fails to
/// deserialize and is recompiled).
pub trait ValueCodec: Sized {
    fn write_value<P: Program>(
        w: &mut Writer,
        value: Self,
        modules: &HashMap<ModuleKey, Arc<StaticModule<P>>>,
    );
    fn read_value<P: Program>(
        r: &mut Reader<'_>,
        self_key: ModuleKey,
        self_arena: &[u8],
        self_base: *const u8,
        modules: &HashMap<ModuleKey, Arc<StaticModule<P>>>,
    ) -> Result<Self, String>;
}

/// Encode/decode one **operator leaf** enum.
pub trait OperatorCodec: Sized {
    fn write_operator(w: &mut Writer, op: Self);
    fn read_operator(r: &mut Reader<'_>) -> Result<Self, String>;
}

/// The aligned base of a module's arena — the same formula
/// `StaticModule::from_module` used to lay the payloads out, so offsets
/// round-trip exactly.
pub fn arena_base(arena: &[u8]) -> *const u8 {
    let ptr = arena.as_ptr() as usize;
    let base = (ptr + ARENA_ALIGN - 1) & !(ARENA_ALIGN - 1);
    base as *const u8
}

/// The base-relative offset of a handle's payload pointer.
pub fn handle_offset<P: Program>(module: &StaticModule<P>, offset: *const u8) -> usize {
    let base = arena_base(&module.arena) as usize;
    let relative = offset as usize - base;
    assert!(
        relative <= module.arena.len(),
        "a handle offset outside its module's arena — broken frozen module"
    );
    relative
}

/// The payload alignment of the frozen arena — array item slices are the only
/// payload kind the core vocabulary uses (a composed value's ext handle
/// variants, if any, become a new payload kind and must be considered by a
/// downstream codec's alignment choice).
pub const ARENA_ALIGN: usize = std::mem::align_of::<ArrayItem>();

// --- the structural leaves ------------------------------------------------------

impl ValueCodec for LowValue {
    fn write_value<P: Program>(
        w: &mut Writer,
        value: Self,
        modules: &HashMap<ModuleKey, Arc<StaticModule<P>>>,
    ) {
        match value {
            LowValue::USize(n) => {
                w.u8(0);
                w.u64(n as u64);
            }
            LowValue::Array(AnyHandle::Static(handle)) => {
                w.u8(1);
                w.u64(handle.module.as_raw());
                let module = &modules[&handle.module];
                let slice = unsafe { &*handle.offset };
                w.u64(handle_offset(module, slice.as_ptr() as *const u8) as u64);
                w.u64(slice.len() as u64);
            }
            LowValue::Array(AnyHandle::Dynamic(_)) => {
                panic!("serializing a frozen module that carries a dynamic array payload")
            }
            LowValue::Table(AnyHandle::Static(handle)) => {
                w.u8(6);
                w.u64(handle.module.as_raw());
                let module = &modules[&handle.module];
                let slice = unsafe { &*handle.offset };
                w.u64(handle_offset(module, slice.as_ptr() as *const u8) as u64);
                w.u64(slice.len() as u64);
            }
            LowValue::Table(AnyHandle::Dynamic(_)) => {
                panic!("serializing a frozen module that carries a dynamic table payload")
            }
            LowValue::Function(AnyFunctionId::Static(function)) => {
                w.u8(2);
                w.u64(function.module.as_raw());
                w.u64(function.index.0 as u64);
            }
            LowValue::Function(AnyFunctionId::Dynamic(_)) => {
                panic!("serializing a frozen module that carries a dynamic function ref")
            }
            LowValue::None => w.u8(3),
            LowValue::Parameterized => w.u8(4),
            LowValue::Str(s) => {
                w.u8(5);
                w.u32(s.len() as u32);
                w.bytes(s.as_bytes());
            }
        }
    }

    fn read_value<P: Program>(
        r: &mut Reader<'_>,
        self_key: ModuleKey,
        self_arena: &[u8],
        self_base: *const u8,
        modules: &HashMap<ModuleKey, Arc<StaticModule<P>>>,
    ) -> Result<Self, String> {
        Ok(match r.u8()? {
            0 => LowValue::USize(r.u64()? as usize),
            1 => {
                let owner = ModuleKey::from_raw(r.u64()?);
                let offset = r.u64()? as usize;
                let len = r.u64()? as usize;
                let (owner_arena, owner_base) = if owner == self_key {
                    (self_arena, self_base)
                } else {
                    let module = modules.get(&owner).ok_or_else(|| {
                        format!("artifact references unregistered dependency key {owner:?}")
                    })?;
                    let arena: &[u8] = &module.arena;
                    (arena, arena_base(arena))
                };
                let gap = owner_base as usize - owner_arena.as_ptr() as usize;
                if offset + len > owner_arena.len() - gap {
                    return Err("artifact handle out of its arena's bounds".into());
                }
                let payload = unsafe { owner_base.add(offset) as *const ArrayItem };
                LowValue::Array(AnyHandle::Static(StaticHandle {
                    module: owner,
                    offset: std::ptr::slice_from_raw_parts(payload, len),
                }))
            }
            2 => {
                let module = ModuleKey::from_raw(r.u64()?);
                let index = r.u64()? as usize;
                LowValue::Function(AnyFunctionId::Static(StaticFunctionRef {
                    module,
                    index: StaticFunctionId(index),
                }))
            }
            3 => LowValue::None,
            4 => LowValue::Parameterized,
            5 => {
                let len = r.u32()? as usize;
                let bytes = r.take(len)?;
                // The value is `Copy` and must outlive the artifact buffer, so
                // the loaded bytes are leaked to a `&'static str` (like a
                // source-built literal).  The content is UTF-8 by construction.
                let s = std::str::from_utf8(bytes).map_err(|_| "string literal is not UTF-8")?;
                LowValue::Str(Box::leak(s.to_string().into_boxed_str()))
            }
            6 => {
                let owner = ModuleKey::from_raw(r.u64()?);
                let offset = r.u64()? as usize;
                let len = r.u64()? as usize;
                let (owner_arena, owner_base) = if owner == self_key {
                    (self_arena, self_base)
                } else {
                    let module = modules.get(&owner).ok_or_else(|| {
                        format!("artifact references unregistered dependency key {owner:?}")
                    })?;
                    let arena: &[u8] = &module.arena;
                    (arena, arena_base(arena))
                };
                let gap = owner_base as usize - owner_arena.as_ptr() as usize;
                if offset + len > owner_arena.len() - gap {
                    return Err("artifact handle out of its arena's bounds".into());
                }
                let payload = unsafe { owner_base.add(offset) as *const TableItem };
                LowValue::Table(AnyHandle::Static(StaticHandle {
                    module: owner,
                    offset: std::ptr::slice_from_raw_parts(payload, len),
                }))
            }
            tag => return Err(format!("unknown lowlevel value tag {tag}")),
        })
    }
}

impl OperatorCodec for LowOperator {
    fn write_operator(w: &mut Writer, op: LowOperator) {
        match op {
            LowOperator::Index => w.u8(0),
            LowOperator::Apply => w.u8(1),
            LowOperator::TableGet => w.u8(2),
        }
    }

    fn read_operator(r: &mut Reader<'_>) -> Result<LowOperator, String> {
        Ok(match r.u8()? {
            0 => LowOperator::Index,
            1 => LowOperator::Apply,
            2 => LowOperator::TableGet,
            tag => return Err(format!("unknown lowlevel operator tag {tag}")),
        })
    }
}
