//! The artifact codec primitives: the byte reader/writer, the per-leaf
//! value/operator codec traits, and the structural leaf codecs.
//!
//! The artifact format (`lichen-language::persist`) is generic over a program's
//! value/operator vocabulary; the only vocabulary-dependent parts are the value
//! and operator encodings.  This module isolates them: each value/operator leaf
//! enum implements [`ValueCodec`]/[`OperatorCodec`] for itself, and a composed
//! vocabulary's `ProgramCodec` (generated by `lichen-language`'s
//! `lang_compose_vocabulary!`) dispatches each carry variant to its leaf's codec.
//!
//! The lowlevel owns the leaf codec protocol because [`LowValue`]'s handle
//! variants need the arena relocation the artifact container provides, and
//! every lower/leaf crate already depends on the lowlevel for those types.

use std::collections::HashMap;
use std::sync::Arc;

use crate::{
    AnyFunctionId, AnyHandle, ArrayItem, LowOperator, LowValue, ModuleKey, Program,
    StaticFunctionId, StaticFunctionRef, StaticHandle, StaticModule, TableItem, ValueExt as _,
};

// --- byte reader / writer -----------------------------------------------------

// The byte reader/writer are type-independent and live in the leaf
// `lichen-registry` crate (`lichen_registry::codec`); re-exported here so the
// existing `liche_lowlevel::codec::{Reader, Writer}` paths keep resolving.
pub use lichen_registry::codec::{Reader, Writer};

// --- the per-leaf codec traits --------------------------------------------------

/// Encode/decode one **value leaf** enum.
///
/// A composed vocabulary's codec writes a leaf discriminator, then delegates to
/// the matching leaf's `write_value`/`read_value`.  A leaf whose variants carry
/// no arena payload (type markers, plugin scalars) ignores the `modules`/
/// `self_*` context; [`LowValue`]'s handle variants need it to relocate.
///
/// **Contract:** the two sides must be exact inverses — every tag the writer
/// emits, the reader decodes to the equal value, and nothing else.  A mismatch
/// compiles but silently breaks every cache load (a stored artifact fails to
/// deserialize and is recompiled).
pub trait ValueCodec: Sized {
    fn write_value<P: Program>(
        w: &mut Writer,
        value: Self,
        modules: &HashMap<ModuleKey, Arc<StaticModule<P>>>,
    );
    fn read_value<P: Program>(
        r: &mut Reader<'_>,
        self_key: ModuleKey,
        self_arena: &[u8],
        self_base: *const u8,
        modules: &HashMap<ModuleKey, Arc<StaticModule<P>>>,
    ) -> Result<Self, String>;
}

/// Encode/decode one **operator leaf** enum.
pub trait OperatorCodec: Sized {
    fn write_operator(w: &mut Writer, op: Self);
    fn read_operator(r: &mut Reader<'_>) -> Result<Self, String>;
}

/// The payload alignment of a program's frozen arena — the strictest
/// alignment any arena payload kind can need: array items, table items, and
/// the program's ext handle payloads ([`ValueExt::alignment`]).  The freeze
/// layout ([`StaticModule::from_module`]) and this codec both derive the
/// arena base from this one function of the program type, so the writer and
/// the reader provably agree; the artifact header records it as a
/// corruption guard.
pub fn arena_align<P: Program>() -> usize {
    std::mem::align_of::<ArrayItem>()
        .max(std::mem::align_of::<TableItem>())
        .max(P::Value::alignment())
}

/// The aligned base of a module's arena — the same formula
/// `StaticModule::from_module` used to lay the payloads out, so offsets
/// round-trip exactly.
pub fn arena_base<P: Program>(arena: &[u8]) -> *const u8 {
    let align = arena_align::<P>();
    let ptr = arena.as_ptr() as usize;
    let base = (ptr + align - 1) & !(align - 1);
    base as *const u8
}

/// The base-relative offset of a handle's payload pointer.
pub fn handle_offset<P: Program>(module: &StaticModule<P>, offset: *const u8) -> usize {
    let base = arena_base::<P>(&module.arena) as usize;
    let relative = offset as usize - base;
    assert!(
        relative <= module.arena.len(),
        "a handle offset outside its module's arena — broken frozen module"
    );
    relative
}

// --- the structural leaves ------------------------------------------------------

/// Rebuild a static handle for an arena payload read out of an artifact.
///
/// The artifact records the payload's **base-relative byte offset** and its
/// **element count** (see [`ValueCodec::write_value`]), so the bound has to be
/// made in bytes, and every step of it checked: a crafted `(offset, len)` pair
/// is a clean `Err`, never a wrap, a panic, or a pointer outside the arena.
///
/// **Contract:** `offset` is a whole number of `Item`s from `owner_base` and
/// the `len * size_of::<Item>()` bytes there are inside `owner_arena` — what
/// the freeze lays out, so every artifact the writer emits satisfies it.
fn relocated_handle<Item>(
    owner: ModuleKey,
    owner_arena: &[u8],
    owner_base: *const u8,
    offset: usize,
    len: usize,
) -> Result<StaticHandle<[Item]>, String> {
    let alignment = std::mem::align_of::<Item>();
    if !offset.is_multiple_of(alignment) {
        return Err("artifact handle is not aligned to its payload type".into());
    }
    let byte_len = len
        .checked_mul(std::mem::size_of::<Item>())
        .ok_or("artifact handle element count overflows its byte length")?;
    let end = offset
        .checked_add(byte_len)
        .ok_or("artifact handle bounds overflow")?;
    let gap = (owner_base as usize)
        .checked_sub(owner_arena.as_ptr() as usize)
        .ok_or("artifact arena base precedes its own buffer")?;
    let available = owner_arena
        .len()
        .checked_sub(gap)
        .ok_or("artifact arena base lies past the end of its buffer")?;
    if end > available {
        return Err("artifact handle out of its arena's bounds".into());
    }
    let payload = unsafe { owner_base.add(offset) as *const Item };
    Ok(StaticHandle {
        module: owner,
        offset: std::ptr::slice_from_raw_parts(payload, len),
    })
}

impl ValueCodec for LowValue {
    fn write_value<P: Program>(
        w: &mut Writer,
        value: Self,
        modules: &HashMap<ModuleKey, Arc<StaticModule<P>>>,
    ) {
        match value {
            LowValue::USize(n) => {
                w.u8(0);
                w.u64(n as u64);
            }
            LowValue::Array(AnyHandle::Static(handle)) => {
                w.u8(1);
                w.u64(handle.module.as_raw());
                let module = &modules[&handle.module];
                let slice = unsafe { &*handle.offset };
                w.u64(handle_offset(module, slice.as_ptr() as *const u8) as u64);
                w.u64(slice.len() as u64);
            }
            LowValue::Array(AnyHandle::Dynamic(_)) => {
                panic!("serializing a frozen module that carries a dynamic array payload")
            }
            LowValue::Table(AnyHandle::Static(handle)) => {
                w.u8(6);
                w.u64(handle.module.as_raw());
                let module = &modules[&handle.module];
                let slice = unsafe { &*handle.offset };
                w.u64(handle_offset(module, slice.as_ptr() as *const u8) as u64);
                w.u64(slice.len() as u64);
            }
            LowValue::Table(AnyHandle::Dynamic(_)) => {
                panic!("serializing a frozen module that carries a dynamic table payload")
            }
            LowValue::Function(AnyFunctionId::Static(function)) => {
                w.u8(2);
                w.u64(function.module.as_raw());
                w.u64(function.index.0 as u64);
            }
            LowValue::Function(AnyFunctionId::Dynamic(_)) => {
                panic!("serializing a frozen module that carries a dynamic function ref")
            }
            LowValue::None => w.u8(3),
            // Tag 7 is additive: artifacts written before `Void` existed
            // never carry it, and tag 3 keeps meaning the `None` unit value.
            LowValue::Void => w.u8(7),
            LowValue::Parameterized => w.u8(4),
            LowValue::Str(s) => {
                w.u8(5);
                w.u32(s.len() as u32);
                w.bytes(s.as_bytes());
            }
        }
    }

    fn read_value<P: Program>(
        r: &mut Reader<'_>,
        self_key: ModuleKey,
        self_arena: &[u8],
        self_base: *const u8,
        modules: &HashMap<ModuleKey, Arc<StaticModule<P>>>,
    ) -> Result<Self, String> {
        Ok(match r.u8()? {
            0 => LowValue::USize(r.u64()? as usize),
            1 => {
                let owner = ModuleKey::from_raw(r.u64()?);
                let offset = r.u64()? as usize;
                let len = r.u64()? as usize;
                let (owner_arena, owner_base) = if owner == self_key {
                    (self_arena, self_base)
                } else {
                    let module = modules.get(&owner).ok_or_else(|| {
                        format!("artifact references unregistered dependency key {owner:?}")
                    })?;
                    let arena: &[u8] = &module.arena;
                    (arena, arena_base::<P>(arena))
                };
                let handle =
                    relocated_handle::<ArrayItem>(owner, owner_arena, owner_base, offset, len)?;
                LowValue::Array(AnyHandle::Static(handle))
            }
            2 => {
                let module = ModuleKey::from_raw(r.u64()?);
                let index = r.u64()? as usize;
                LowValue::Function(AnyFunctionId::Static(StaticFunctionRef {
                    module,
                    index: StaticFunctionId(index),
                }))
            }
            3 => LowValue::None,
            7 => LowValue::Void,
            4 => LowValue::Parameterized,
            5 => {
                let len = r.u32()? as usize;
                let bytes = r.take(len)?;
                // The value is `Copy` and must outlive the artifact buffer, so
                // the loaded bytes are leaked to a `&'static str` (like a
                // source-built literal).  The content is UTF-8 by construction.
                let s = std::str::from_utf8(bytes).map_err(|_| "string literal is not UTF-8")?;
                LowValue::Str(Box::leak(s.to_string().into_boxed_str()))
            }
            6 => {
                let owner = ModuleKey::from_raw(r.u64()?);
                let offset = r.u64()? as usize;
                let len = r.u64()? as usize;
                let (owner_arena, owner_base) = if owner == self_key {
                    (self_arena, self_base)
                } else {
                    let module = modules.get(&owner).ok_or_else(|| {
                        format!("artifact references unregistered dependency key {owner:?}")
                    })?;
                    let arena: &[u8] = &module.arena;
                    (arena, arena_base::<P>(arena))
                };
                let handle =
                    relocated_handle::<TableItem>(owner, owner_arena, owner_base, offset, len)?;
                LowValue::Table(AnyHandle::Static(handle))
            }
            tag => return Err(format!("unknown lowlevel value tag {tag}")),
        })
    }
}

impl OperatorCodec for LowOperator {
    fn write_operator(w: &mut Writer, op: LowOperator) {
        match op {
            LowOperator::Index => w.u8(0),
            LowOperator::Apply => w.u8(1),
            LowOperator::TableGet => w.u8(2),
        }
    }

    fn read_operator(r: &mut Reader<'_>) -> Result<LowOperator, String> {
        Ok(match r.u8()? {
            0 => LowOperator::Index,
            1 => LowOperator::Apply,
            2 => LowOperator::TableGet,
            tag => return Err(format!("unknown lowlevel operator tag {tag}")),
        })
    }
}
